# Generated by Django 4.1.7 on 2023-03-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_coupon_order_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Coupon',
            new_name='coupon',
        ),
    ]
